# Generated by Django 4.2.1 on 2023-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=100)),
                ("sid", models.IntegerField()),
                ("smarks", models.IntegerField()),
                ("tname", models.CharField(max_length=100)),
            ],
        ),
    ]
